"""migrations

Revision ID: a0da0dc2cc65
Revises: f3d65f566819
Create Date: 2026-03-11 06:53:28.245469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0da0dc2cc65'
down_revision = 'f3d65f566819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('items_denormalized',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=True),
    sa.Column('supplier_email', sa.String(length=200), nullable=True),
    sa.Column('supplier_phone', sa.String(length=50), nullable=True),
    sa.Column('supplier_contact', sa.String(length=200), nullable=True),
    sa.Column('location_name', sa.String(length=100), nullable=True),
    sa.Column('location_zone', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('current_stock >= 0', name='check_denorm_stock_positive'),
    sa.CheckConstraint('unit_price >= 0', name='check_denorm_price_positive'),
    sa.PrimaryKeyConstraint('item_id')
    )
    with op.batch_alter_table('items_denormalized', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_denormalized_category_name'), ['category_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_denormalized_current_stock'), ['current_stock'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_denormalized_item_code'), ['item_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_items_denormalized_item_name'), ['item_name'], unique=False)

    op.create_table('locations',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('warehouse', sa.String(length=50), nullable=False),
    sa.Column('aisle', sa.String(length=20), nullable=True),
    sa.Column('shelf', sa.String(length=20), nullable=True),
    sa.Column('bin', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_table('transaction_types',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('type_id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('transactions_denormalized',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=True),
    sa.Column('supplier_name', sa.String(length=200), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.CheckConstraint('quantity > 0', name='check_denorm_qty_positive'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    with op.batch_alter_table('transactions_denormalized', schema=None) as batch_op:
        batch_op.create_index('idx_denorm_item_date', ['item_code', 'transaction_date'], unique=False)
        batch_op.create_index('idx_denorm_type_date', ['transaction_type', 'transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_denormalized_item_code'), ['item_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_denormalized_transaction_date'), ['transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_denormalized_transaction_type'), ['transaction_type'], unique=False)

    op.create_table('items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('current_stock >= 0', name='check_stock_positive'),
    sa.CheckConstraint('reorder_level >= 0', name='check_reorder_positive'),
    sa.CheckConstraint('unit_price >= 0', name='check_price_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_current_stock'), ['current_stock'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_item_code'), ['item_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_items_item_name'), ['item_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.CheckConstraint('quantity > 0', name='check_quantity_positive'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['transaction_types.type_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_item_date', ['item_id', 'transaction_date'], unique=False)
        batch_op.create_index('idx_type_date', ['type_id', 'transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_date'), ['transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_type_id'), ['type_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_type_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_item_id'))
        batch_op.drop_index('idx_type_date')
        batch_op.drop_index('idx_item_date')

    op.drop_table('transactions')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_items_item_name'))
        batch_op.drop_index(batch_op.f('ix_items_item_code'))
        batch_op.drop_index(batch_op.f('ix_items_current_stock'))
        batch_op.drop_index(batch_op.f('ix_items_category_id'))

    op.drop_table('items')
    with op.batch_alter_table('transactions_denormalized', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_denormalized_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_denormalized_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_denormalized_item_code'))
        batch_op.drop_index('idx_denorm_type_date')
        batch_op.drop_index('idx_denorm_item_date')

    op.drop_table('transactions_denormalized')
    op.drop_table('transaction_types')
    op.drop_table('suppliers')
    op.drop_table('locations')
    with op.batch_alter_table('items_denormalized', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_denormalized_item_name'))
        batch_op.drop_index(batch_op.f('ix_items_denormalized_item_code'))
        batch_op.drop_index(batch_op.f('ix_items_denormalized_current_stock'))
        batch_op.drop_index(batch_op.f('ix_items_denormalized_category_name'))

    op.drop_table('items_denormalized')
    op.drop_table('categories')
    # ### end Alembic commands ###
