"""added denormalization

Revision ID: f3d65f566819
Revises: 6f19a4fd60e5
Create Date: 2026-03-10 10:40:39.789051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d65f566819'
down_revision = '6f19a4fd60e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items_denormalized',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=True),
    sa.Column('supplier_email', sa.String(length=200), nullable=True),
    sa.Column('supplier_phone', sa.String(length=50), nullable=True),
    sa.Column('supplier_contact', sa.String(length=200), nullable=True),
    sa.Column('location_name', sa.String(length=100), nullable=True),
    sa.Column('location_zone', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('current_stock >= 0', name='check_denorm_stock_positive'),
    sa.CheckConstraint('unit_price >= 0', name='check_denorm_price_positive'),
    sa.PrimaryKeyConstraint('item_id')
    )
    with op.batch_alter_table('items_denormalized', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_denormalized_category_name'), ['category_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_denormalized_current_stock'), ['current_stock'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_denormalized_item_code'), ['item_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_items_denormalized_item_name'), ['item_name'], unique=False)

    op.create_table('transactions_denormalized',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=True),
    sa.Column('supplier_name', sa.String(length=200), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.CheckConstraint('quantity > 0', name='check_denorm_qty_positive'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    with op.batch_alter_table('transactions_denormalized', schema=None) as batch_op:
        batch_op.create_index('idx_denorm_item_date', ['item_code', 'transaction_date'], unique=False)
        batch_op.create_index('idx_denorm_type_date', ['transaction_type', 'transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_denormalized_item_code'), ['item_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_denormalized_transaction_date'), ['transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_denormalized_transaction_type'), ['transaction_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions_denormalized', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_denormalized_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_denormalized_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_denormalized_item_code'))
        batch_op.drop_index('idx_denorm_type_date')
        batch_op.drop_index('idx_denorm_item_date')

    op.drop_table('transactions_denormalized')
    with op.batch_alter_table('items_denormalized', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_denormalized_item_name'))
        batch_op.drop_index(batch_op.f('ix_items_denormalized_item_code'))
        batch_op.drop_index(batch_op.f('ix_items_denormalized_current_stock'))
        batch_op.drop_index(batch_op.f('ix_items_denormalized_category_name'))

    op.drop_table('items_denormalized')
    # ### end Alembic commands ###
